import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Web3 ship to next</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div>Home</div>
    </>
  );
};
export default Home;
